### ISSUE TITLE
Where is ArmadaVagrantfile.rb?

### ISSUE THREAD

**Issue by ryneeverett** [armadaplatform/armada-website#20]
I would have assumed it would be in this repository but I can't find it.

**Comment by fwojciak** [comment]
It's in [vagrant](https://github.com/armadaplatform/vagrant) repository:
https://github.com/armadaplatform/vagrant/blob/master/src/static/ArmadaVagrantfile.rb

**Comment by ryneeverett** [comment]
@fwojciak Thanks!
